#!/bin/bash
# Composites recorded frames into docs/poolside-demo.mp4 and docs/poolside-demo.gif.
#
#   bash Tools/Recording/compose.sh [frames-dir]
#
# Needs Node 18+ and pnpm. Run record-demo.sh first.
set -euo pipefail
cd "$(dirname "$0")"
FRAMES="$(cd "${1:-../../.build/recording/frames}" && pwd)"
rm -rf video/public/frames && mkdir -p video/public/frames
cp "$FRAMES"/*.png video/public/frames/
cp backdrop.webp video/public/backdrop.webp
python3 - "$FRAMES" video/src/frames.gen.ts <<'PY'
import sys
d, out = sys.argv[1], sys.argv[2]
clock = float(open(f"{d}/clock.txt").read())
rows = sorted((float(t) - clock, int(i)) for i, t in (l.split() for l in open(f"{d}/timings.txt") if l.strip()))
open(out, "w").write("// Generated by compose.sh: [demo seconds, frame index].\nexport const FRAMES: [number, number][] = " + str([[round(t, 4), i] for t, i in rows]) + ";\n")
PY
cd video
pnpm install --frozen-lockfile 2>/dev/null || pnpm install
pnpm run demo
pnpm run gif
